receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:4318
        cors:
          allowed_origins:
            - "*"

processors:
  batch:

exporters:
  otlp:
    endpoint: "api-dogfood.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "$HONEYCOMB_API_KEY"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
