receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"

processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_mib: 600
  resourcedetection:
    detectors: [system]

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: https://api-dogfood.honeycomb.io:443
    headers:
      "x-honeycomb-team": "$HONEYCOMB_API_KEY"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter, resourcedetection]
      exporters: [otlp]
