receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://localhost:8080
            - http://express-server:8080
            # - "*"
          # allowed_headers:
          #   - "*"
            # - "Access-Control-Request-Headers"
            # - "Access-Control-Request-Method"
            # - "content-type"
            # - "Origin"
            # - "X-Honeycomb-Team"

processors:
  batch:

exporters:
  otlp:
    endpoint: https://api-dogfood.honeycomb.io:443
    headers:
      # If testing start by using the key inline, to eliminate environment issues
      # "x-honeycomb-team": "< your key here >"
      # In this case, pull from env.
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"

service:
  telemetry:
    logs:
      level: "INFO"
      # development: true
      encoding: "json"
  pipelines:
    traces:
      receivers: [otlp]
      # processors: [batch, memory_limiter, resourcedetection]
      processors: [batch]
      # exporters: [debug,otlp]
      exporters: [otlp]
