services:
  nginx-react:
    container_name: react-app
    build:
      context: packages/client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production

  appserver:
    container_name: express_server
    build:
      context: packages/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  # otel-validator:
  #   image: otel/opentelemetry-collector-contrib
  #   volumes:
  #     - ./packages/otel-collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
  #   environment:
  #     HONEYCOMB_API_KEY: $HONEYCOMB_API_KEY
  #   entrypoint:
  #     [otelcol-contrib validate --config /etc/ottelcol-contrib/config.yaml]

  otel-collector:
    # depends_on:
    #   - otel-validator
    container_name: otel-collector-man
    image: otel/opentelemetry-collector:0.114.0
    # image: otel/opentelemetry-collector
    volumes:
      # n.b. depending on which collector you use (contrib or standard) the directory 
      # used to access the collector config changes, so the volume must change as well
      #- ./packages/otel-collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
      - ./packages/otel-collector/otel-collector-config.yaml:/etc/otelcol/config.yaml
    environment:
      HONEYCOMB_API_KEY: $HONEYCOMB_API_KEY
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
