services:
  nginx-react:
    container_name: react-app
    build:
      context: packages/client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production

  appserver:
    container_name: express_server
    build:
      context: packages/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.114.0
    volumes:
      - ./packages/otel-collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    environment:
      HONEYCOMB_API_KEY: $HONEYCOMB_API_KEY
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
